apiVersion: v1
kind: Service
metadata:
  labels:
    app: weshopify-zipkin-service
  name: weshopify-zipkin-service
spec:
  type: NodePort
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    app: weshopify-zipkin-service
status:
  loadBalancer: {}
