apiVersion: v1
kind: Service
metadata:
  labels:
    app: weshopify-registry-svc
  name: weshopify-registry-svc
spec:
  type: NodePort
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: weshopify-registry-svc
status:
  loadBalancer: {}
