apiVersion: v1
kind: Service
metadata:
  labels:
    app: weshopify-cache-svc
  name: weshopify-cache-svc
spec:
  type: NodePort
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: weshopify-cache-svc
status:
  loadBalancer: {}
